const universityNames = [
    "Louisiana State University",
    "Arcadia University",
    "Roanoke College",
    "Temple University",
    "The Ohio State University",
    "University of Exeter",
    "Wilfrid Laurier University",
    "Bellarmine University",
    "University of Hawaii at Manoa",
    "University of Nevada, Reno",
    "University of New Mexico",
    "Western Carolina University",
    "Lancaster University",
    "King's College London",
    "American University",
    "The University of Hong Kong",
    "The George Washington University",
    "Saint Mary's College",
    "University of Manchester",
    "Frankfurt University of Applied Sciences",
    "University of Applied Sciences and Arts North",
    "Lund University",
    "University of the Fraser Valley",
    "Alverno College",
    "University of Massachusetts Amherst",
    "NHL Stenden University of Applied Sciences",
    "Osnabrück University",
    "Ritsumeikan Asia Pacific University",
    "Sapienza University of Rome",
    "Sciences Po Rennes",
    "Sciences Po Lille",
    "Tatung University",
    "Kansai Gaidai University",
    "National Taiwan University",
    "National Taiwan Normal University",
    "University of Applied Sciences Upper Austria",
    "Universidad Carlos III de Madrid",
    "Hochschule Düsseldorf - University of Applied Sciences",
    "University of Navarra",
    "Karelia University of Applied Sciences",
    "University of Strasbourg",
    "University of New South Wales",
    "Kwansei Gakuin University",
    "Ca' Foscari University of Venice",
    "Abat Oliba CEU University",
    "Mykolas Romeris University",
    "Fukuoka University",
    "Paris 1 University Panthéon-Sorbonne",
    "IHECS",
    "Freie Universitat Berlin",
    "University of Bergen",
    "Université de Versailles Saint Quentin en Yvelines",
    "Maastricht University School of Business and Economics",
    "Amsterdam University of Applied Sciences",
    "Osaka University of Economics and Law",
    "The Hong Kong University of Science and Technology",
    "Momoyama Gakuin University",
    "University of Rostock",
    "University of Jyväskylä",
    "University of Caen",
    "Toyo Eiwa University",
    "Faculty of Arts, KU Leuven",
    "Technical University of Darmstadt",
    "Roskilde University",
    "Autonomous University of Barcelona",
    "Peking University, China",
    "La Trobe University",
    "University of Santiago de Compostela",
    "ISEP Study Abroad",
    "York University",
    "The University of Iowa",
    "University of Central Lancashire",
    "Smith College",
    "Catholic University of Lille",
    "University of Bologna",
    "Fu Jen Catholic University",
    "European University Flensburg",
    "Oita University",
    "Ritsumeikan University",
    "Paris School of Business",
    "Keio University",
    "Rikkyo University",
    "Martin-Luther-University Halle-Wittenberg",
    "Uppsala University",
    "Nara Women's University",
    "Tamkang University",
    "Nagoya University",
    "Willamette University",
    "California State University Dominguez Hills",
    "Kwassui Women's University",
    "Inalco (Institut national des langues et civilisations orientales)",
    "Bern University of Applied Sciences (BFH)",
    "Osaka Kyoiku University",
    "Singapore Management University",
    "Sciences Po",
    "Tokyo University of Foreign Studies",
    "Shigakkan University",
    "Ghent University"
];

const country = [
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "United Kingdom",
    "Canada",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "United Kingdom",
    "United Kingdom",
    "United States",
    "Hong Kong",
    "USA",
    "USA",
    "United Kingdom",
    "Germany",
    "Switzerland",
    "Sweden",
    "Canada",
    "USA",
    "USA",
    "The Netherlands",
    "Germany",
    "Japan",
    "Italy",
    "France",
    "France",
    "Taiwan",
    "Japan",
    "Taiwan",
    "Taiwan",
    "Austria",
    "Spain",
    "Germany",
    "Spain",
    "Finland",
    "France",
    "Australia",
    "Japan",
    "Italy",
    "Spain",
    "Lithuania",
    "Japan",
    "France",
    "Belgium",
    "Germany",
    "Norway",
    "France",
    "The Netherlands",
    "The Netherlands",
    "Japan",
    "Hong Kong",
    "Japan",
    "Germany",
    "Finland",
    "France",
    "Japan",
    "Belgium",
    "Germany",
    "Denmark",
    "Spain",
    "China",
    "Australia",
    "Spain",
    "Worldwide",
    "Canada",
    "USA",
    "United Kingdom",
    "USA",
    "France",
    "Italy",
    "Taiwan",
    "Germany",
    "Japan",
    "Japan",
    "France",
    "Japan",
    "Japan",
    "Germany",
    "Sweden",
    "Japan",
    "Taiwan",
    "Japan",
    "USA",
    "USA",
    "Japan",
    "France",
    "Switzerland",
    "Japan",
    "Singapore",
    "France",
    "Japan",
    "Japan",
    "Belgium"
];

const city = [
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "Exeter",
    "Waterloo, Ontario",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "Lancashire",
    "London",
    "USA",
    "Hong Kong",
    "USA",
    "USA",
    "Manchester",
    "Frankfurt",
    "Basel, Olten, Brugg-Windisch",
    "Lund",
    "Abbotsford, British Columbia",
    "USA",
    "USA",
    "Leeuwarden",
    "Osnabrück",
    "Oita (Beppu)",
    "Rome",
    "Rennes",
    "Lille",
    "Taipei",
    "Hirakata",
    "Taipei City",
    "Taipei",
    "Steyr and Wels",
    "Madrid",
    "Düsseldorf",
    "Pamplona",
    "Joensuu",
    "Strasbourg",
    "NSW, Sydney",
    "Nishinomiya, Japan",
    "Venice",
    "Barcelona",
    "Vilnius",
    "Fukuoka City",
    "Paris",
    "Brussels",
    "Berlin",
    "Norway",
    "Versailles",
    "Maastricht",
    "Amsterdam",
    "Osaka Yao",
    "Hong Kong",
    "Izumi-cuty, Osaka",
    "Rostock",
    "Jyväskylä",
    "Caen",
    "Yokohama, Kanagawa",
    "Leuven",
    "Darmstadt",
    "Roskilde",
    "Barcelona",
    "Beijing",
    "Melbourne",
    "Santiago de Compostela ( La Coruña)",
    "Worldwide",
    "Toronto",
    "USA",
    "Preston",
    "USA",
    "Lille",
    "Bologna",
    "New Taipei City",
    "Flensburg",
    "Oita city",
    "Kyoto",
    "Paris",
    "Tokyo",
    "Tokyo",
    "Halle (Saale)",
    "Uppsala",
    "Nara",
    "Taipei",
    "Nagoya, Aichi Prefecture",
    "USA",
    "USA",
    "Nagasaki city, Nagasaki",
    "Paris",
    "Bern",
    "Osaka",
    "Singapore",
    "PARIS",
    "Tokyo",
    "Aichi",
    "Ghent"
];

const grade = [
    2.5,
    3,
    3,
    3,
    3,
    3,
    0,
    1,
    2.5,
    2.75,
    3,
    0,
    3,
    3.3,
    3,
    3.33,
    3,
    3.3,
    0,
    3,
    0,
    0,
    0,
    3,
    3,
    0,
    0,
    2,
    0,
    0,
    0,
    0,
    3,
    3,
    3,
    2.8,
    0,
    0,
    2.7,
    0,
    0,
    3,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1.5,
    0,
    0,
    2.5,
    0,
    0,
    0,
    0,
    0,
    3.5,
    2.5,
    0,
    0,
    2.5,
    2.5,
    0,
    3,
    2.75,
    0,
    0,
    0,
    0,
    3,
    2.3,
    3,
    0,
    0,
    0,
    0,
    2,
    3,
    3,
    2.5,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    0,
    0
];

const language = [
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '독일어권',
    '스웨덴어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '독일어권',
    '일어권',
    '이탈리아어권',
    '불어권',
    '불어권',
    '중어권',
    '영어권',
    '중어권',
    '중어권',
    '영어권',
    '스페인어권',
    '독일어권',
    '스페인어권',
    '핀란드어권',
    '불어권',
    '영어권',
    '일어권',
    '이탈리아어권',
    '스페인어권',
    '리투아니아어권',
    '일어권',
    '불어권',
    '불어권',
    '독일어권',
    '노르웨이어권',
    '불어권',
    '영어권',
    '네덜란드어권',
    '일어권',
    '영어권',
    '일어권',
    '독일어권',
    '영어권',
    '불어권',
    '일어권',
    '네덜란드어권',
    '독일어권',
    '덴마크어권',
    '스페인어권',
    '중어권',
    '영어권',
    '스페인어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    '불어권',
    '이탈리아어권',
    '중어권',
    '독일어권',
    '일어권',
    '영어권',
    '불어권',
    '일어권',
    '일어권',
    '독일어권',
    '스웨덴어권',
    '일어권',
    '중어권',
    '일어권',
    '영어권',
    '영어권',
    '일어권',
    '불어권',
    '독일어권',
    '일어권',
    '영어권',
    '불어권',
    '일어권',
    '일어권',
    '영어권'
];

const language2 = [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    '영어권',
    '영어권',
    null,
    null,
    null,
    null,
    '영어권',
    '영어권',
    null,
    '영어권',
    '영어권',
    null,
    null,
    '영어권',
    '영어권',
    null,
    '영어권',
    '영어권',
    '영어권',
    '영어원',
    '영어권',
    null,
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    null,
    null,
    '영어권',
    null,
    '영어권',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    '영어권',
    null,
    '영어권',
    '영어권',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    '영어권',
    '영어권',
    '영어권',
    '영어권',
    null,
    '영어권',
    '영어권',
    '영어권',
    null,
    '영어권',
    null,
    '영어권',
    '영어권',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    '영어권',
    '영어권',
    null,
    null
];

const dormitory = [
    "Guaranteed, but students need to apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, and students do not need to apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Guaranteed for full-year students",
    "Not guaranteed, but students can apply",
    "An official score report from one of the following: i.",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, but students need to apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, and students do not need to apply",
    "Guaranteed for full-year students",
    "Guaranteed, but students need to apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, but students need to apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, and students do not need to apply",
    "We have an intermediary service which can help students in finding private accommodation.",
    "Not guaranteed, but students can apply",
    "Students need to find their own housing by themselves.",
    "Guaranteed, but students need to apply",
    "Guaranteed, and students do not need to apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Students need to find their own housing by themselves.",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Students need to find their own housing by themselves.",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "The student will be supported in the search for accommodation by Ca’ Foscari University Housing Office.",
    "Students need to find their own housing by themselves.",
    "Guaranteed, but students need to apply",
    "Guaranteed, and students do not need to apply",
    "Not guaranteed, but students can apply",
    "Students need to find their own housing by themselves.",
    "Not guaranteed, but students can apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, but students need to apply",
    "Students need to find their own housing by themselves.",
    "Not guaranteed, but students can apply",
    "Guaranteed, and students do not need to apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, and students do not need to apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, but students need to apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Varies by location; Guaranteed on Exchange and students may or may not need to apply; Usually guaranteed on Direct; however, some programs do not include housing.",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, but students need to apply",
    "Guaranteed, and students do not need to apply",
    "Not guaranteed, but students can apply",
    "Students need to find their own housing by themselves.",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, and students do not need to apply",
    "Not guaranteed, but students can apply",
    "Students need to find their own housing by themselves.",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, and students do not need to apply",
    "Not guaranteed, but students can apply",
    "Guaranteed, but students need to apply. Application must be submitted on time and meet all the housing requirements within the time frame provided by on-campus housing.",
    "Guaranteed, but students need to apply",
    "Not guaranteed, but students can apply",
    "Students need to find their own housing by themselves.",
    "Guaranteed, and students do not need to apply",
    "No campus housing, but we will give students a list of private housing to consider and apply for by themselves.",
    "Depending on Campus",
    "Not guaranteed, but students can apply",
    "Guaranteed but only for female students",
    "Not guaranteed, but students can apply"
];

const websiteLinks = [
    'https://www.lsu.edu/intlpro/',
    'https://www.arcadia.edu/life-arcadia/get-invo',
    'https://www.roanoke.edu/inside/international_',
    'globalprograms.temple.edu',
    'https://oia.osu.edu/units/international-stude',
    'https://www.exeter.ac.uk/study/studyabroadpro',
    'https://students.wlu.ca/academics/global-enga',
    'https://www.bellarmine.edu/international/',
    'https://manoa.hawaii.edu/mix/',
    'https://www.unr.edu/',
    'https://isss.unm.edu/',
    'https://www.wcu.edu/learn/office-of-international-programs-and-services/',
    'https://www.lancaster.ac.uk/study/international-students/',
    'www.kcl.ac.uk/abroad',
    'https://www.american.edu/abroadatau/',
    'https://intlaffairs.hku.hk/exchange',
    'https://studyabroad.gwu.edu/inbound-exchange-program',
    'https://www.saintmarys.edu/cwil/j-1-exchange-program',
    'Direct link to the program webpage',
    'https://www.frankfurt-university.de/en/studies/international/study-at-fra-uas/exchange-students',
    'https://www.fhnw.ch/en/degree-programmes/business',
    'www.lunduniversity.lu.se/exchange-studies',
    'https://international.ufv.ca/study-abroad-students/',
    'https://www.alverno.edu/IIC-Degree-Seeking-International-Students/',
    'https://www.umass.edu/ipo/iss/exchange-students',
    'https://www.nhlstenden.com/en/why-nhl-stenden',
    'https://www.uni-osnabrueck.de/en/prospective-students/international-prospective-students/exchange-an',
    'https://en.apu.ac.jp/abroad/prospective/incoming/',
    'https://www.uniroma1.it/en/pagina/bilateral-agreements',
    'https://www.sciencespo-rennes.fr/en/international/',
    'https://www.sciencespo-lille.com/prospective-students/exchange-students',
    'https://ao.ttu.edu.tw/p/412-1073-2311.php',
    'https://www.kansaigaidai.ac.jp/asp/',
    'https://oia.ntu.edu.tw/en/internationalstuden',
    'https://bds.oia.ntnu.edu.tw/bds/en/IE',
    'https://www.fh-ooe.at/campus-steyr/internatio',
    'https://www.uc3m.es/studies/international-exc',
    'https://www.hs-duesseldorf.de/prospectivestud',
    'https://www.unav.edu/estudiantes/programas-de',
    'https://www.karelia.fi/en/new-students/exchange-students/',
    'https://www.unistra.fr/international/venir-a-',
    'https://www.unsw.edu.au/study/international-s',
    'https://ciec.kwansei.ac.jp/study/exchange/',
    'https://www.unive.it/pag/12574/',
    'https://www.uaoceu.es/',
    'https://www.mruni.eu/en/university/internatio',
    'https://www.kokusai.fukuoka-u.ac.jp/en/inboun',
    'https://international.pantheonsorbonne.fr/en/',
    'https://www.ihecs.be/fr/come-and-study-ihecs/',
    'https://www.fu-berlin.de/en/studium/internati',
    'www.uib.no/exchange',
    'https://www.uvsq.fr/exchange-programs-1',
    'https://www.maastrichtuniversity.nl/education',
    'https://www.amsterdamuas.com/study/education/',
    'https://www.keiho-u.ac.jp/life/applications/',
    'https://studyabroad.hkust.edu.hk/inbound',
    'https://www.andrew.ac.jp/i-center/exchange_st',
    'https://www.uni-rostock.de/en/study/internati',
    'https://www.jyu.fi/en/study-with-us/student-e',
    'https://www.unicaen.fr/international/bienvenu',
    'https://www.toyoeiwa.ac.jp/daigaku/kokusai/ho',
    'https://www.arts.kuleuven.be/english/educatio',
    'www.tu-darmstadt.de/incoming',
    'https://ruc.dk/en/admission-exchange',
    'https://www.uab.cat/web/mobility-internationa',
    'http://www.oir.pku.edu.cn/en/',
    'https://www.latrobe.edu.au/international/stud',
    'no',
    'https://yorkinternational.yorku.ca/global-lea',
    'https://international.uiowa.edu/ISSS/new-stud',
    'https://www.uclan.ac.uk/study/global-opportun',
    'https://www.smith.edu/your-campus/offices-ser',
    'https://www.univ-catholille.fr/en/erasmus-exc',
    'https://www.unibo.it/en/international/incomin',
    'http://isc.oie.fju.edu.tw/teachingServicesEN.',
    'https://www.uni-flensburg.de/en/international',
    'https://www.gaia.oita-u.ac.jp/en/',
    'https://en.ritsumei.ac.jp/skp/',
    'https://www.psbedu.paris/en/programs/exchange',
    'https://www.ic.keio.ac.jp/en/study/exchange/c',
    'https://sites.google.com/rikkyo.ac.jp/rikkyou',
    'https://www.international.uni-halle.de/intern',
    'https://www.uu.se/en/study/exchange-studies',
    'https://www.nara-wu.ac.jp/iec/int/en/study/fo',
    'http://www.oieie.tku.edu.tw/?locale=en',
    'https://nupace.iee.nagoya-u.ac.jp/en/',
    'https://willamette.edu/offices/oie/index.html',
    'http://kwassui-int.ac.jp/international-servic',
    'no',
    'https://www.bfh.ch/en/studies/international-s',
    'https://ger.osaka-kyoiku.ac.jp/for-prospectiv',
    'https://www.sciencespo.fr/international/en/co',
    'https://www.tufs.ac.jp/english/admission/non-',
    'no',
    'https://www.ugent.be/eb/en/exchange-student/o'
];

const scheduleLinks = [
    "https://www.lsu.edu/registrar/academics/acade",
    "https://www.arcadia.edu/academics/resources/a",
    "https://www.roanoke.edu/inside/registrar/acad",
    "https://registrar.temple.edu/academic-calenda",
    "https://registrar.osu.edu/staff/bigcal.asp",
    "https://www.exeter.ac.uk/staff/policies/calen",
    "https://students.wlu.ca/academics/calendars-a",
    "https://www.bellarmine.edu/registrar/academic",
    "https://manoa.hawaii.edu/mix/wp-content/uploa",
    "https://www.unr.edu/admissions/records/academ",
    "https://registrar.unm.edu/academic-calendar/t",
    "https://www.wcu.edu/_files/learn/Academic_Cal",
    "https://portal.lancaster.ac.uk/ask/term-dates",
    "https://self-service.kcl.ac.uk/article/KA-019",
    "https://www.american.edu/provost/registrar/ac",
    "https://aas.hku.hk/important-academic-dates/",
    "https://www.gwu.edu/academic-calendar",
    "https://www.saintmarys.edu/academics/resource",
    "https://www.dropbox.com/sh/i977xucl7beugpm/AA",
    "https://www.frankfurt-university.de/en/studie",
    "https://www.fhnw.ch/plattformen/iobusiness/ex",
    "https://www.lunduniversity.lu.se/calendar",
    "https://www.ufv.ca/calendar/current/",
    "https://www.alverno.edu/files/galleries/20232",
    "https://www.umass.edu/registrar/calendars/aca",
    "https://www.uni-osnabrueck.de/studium/termine",
    "https://en.apu.ac.jp/academic/academic_inform",
    "https://www.uniroma1.it/en/pagina/academic-ca",
    "https://www.sciencespo-lille.eu/sites/default",
    "https://ao.ttu.edu.tw/p/412-1073-2436.php",
    "https://www.kansaigaidai.ac.jp/asp/academics/",
    "https://www.aca.ntu.edu.tw/w/acaEN/Calendar",
    "https://www.aa.ntnu.edu.tw/zh_tw/Calender",
    "https://www.fh-ooe.at/campus-steyr/internatio",
    "https://www.uc3m.es/bachelor-degree/practical",
    "https://www.hs-duesseldorf.de/prospectivestud",
    "https://www.unav.edu/documents/10162/41521534",
    "https://www.karelia.fi/en/academic-year/",
    "https://www.unistra.fr/formation/admission-in",
    "https://www.student.unsw.edu.au/calendar",
    "https://ciec.kwansei.ac.jp/study/exchange/",
    "https://www.unive.it/pag/36141/",
    "http://www.fu-berlin.de/en/studium/studienorg",
    "https://www.uib.no/en/education/49211/semeste",
    "https://www.uvsq.fr/calendriers-universitaire",
    "https://www.amsterdamuas.com/study/internatio",
    "https://www.keiho-u.ac.jp/faculty/calendar/",
    "https://registry.hkust.edu.hk/resource-librar",
    "https://www.uni-rostock.de/en/study/study-org",
    "https://www.jyu.fi/en/for-students/kandi-ja-m",
    "https://www.toyoeiwa.ac.jp/daigaku/about/gaku",
    "https://www.kuleuven.be/english/about-kuleuve",
    "https://www.tu-darmstadt.de/studieren/studier",
    "https://ruc.dk/en/visitingstudents",
    "https://www.uab.cat/web/studies/undergraduate",
    "https://www.pku.edu.cn/de",
    "https://www.latrobe.edu.au/calendar/academic-",
    "https://registrar.yorku.ca/enrol/dates",
    "https://registrar.uiowa.edu/calendars-deadlin",
    "https://www.smith.edu/academics/academic-cale",
    "https://www.univ-catholille.fr/sites/default/",
    "http://www.unibo.it/en/teaching/course-timeta",
    "http://isc.oie.fju.edu.tw/teachingServicesEN.",
    "https://www.uni-flensburg.de/en/academics/dat",
    "https://www.gaia.oita-u.ac.jp/en/academic/yot",
    "https://en.ritsumei.ac.jp/skp/academics/acade",
    "https://www.ic.keio.ac.jp/en/study/exchange/a",
    "https://sites.google.com/rikkyo.ac.jp/rikkyou",
    "https://www.prorektoratsl.uni-halle.de/1101_7",
    "https://www.uu.se/en/study/higher-education-i",
    "https://english.tku.edu.tw/Calendar.asp",
    "https://nupace.iee.nagoya-u.ac.jp/en/academic",
    "https://willamette.edu/offices/registrar/cale",
    "https://www.csudh.edu/academic-affairs/academ",
    "http://www.inalco.fr/formations/emplois-temps",
    "https://www.bfh.ch/en/studies/study-at-bfh/",
    "https://osaka-kyoiku.ac.jp/Portals/0/files/ca",
    "https://courses.smu.edu.sg/sites/courses.smu.",
    "https://acrobat.adobe.com/link/review?uri=urn",
    "https://www.tufs.ac.jp/english/student/calend",
    "https://www.sgk.ac.jp/campus-life/class/timet",
    "https://www.ugent.be/student/en/class-exam-ex",
];

const email = [
    'exchanges@lsu.edu',
    'doylej@arcadia.edu',
    'lupton@roanoke.edu',
    'global.programs@temple.edu',
    'omolesky.2@osu.edu',
    'Inbound@Exeter.ac.uk',
    'incomingexchange@wlu.ca',
    'mgrandinetti@bellarmine.edu',
    'inbound@hawaii.edu',
    'clindloff@unr.edu',
    'exchange@unm.edu',
    'zforrest@wcu.edu',
    'studyabroad@lancaster.ac.uk',
    'studyabroad@kcl.ac.uk',
    'abroadatau@american.edu',
    'exchange@hku.hk',
    'inbound2gw@gwu.edu',
    'abroad@saintmarys.edu',
    'exchangestudy@manchester.ac.uk',
    'incoming.exchange@io.fra-uas.de',
    'irene.diez@fhnw.ch',
    'studyabroad@ufv.ca',
    'elena.burke@alverno.edu',
    'ipoexchange@umass.edu',
    'io@nhlstenden.com',
    'incoming@uos.de',
    'inbound@apu.ac.jp',
    'intstudex@uniroma1.it',
    'incoming@sciencespo-rennes.fr',
    'international.students@sciencespo-lille.eu',
    'mandyliu@gm.ttu.edu.tw',
    'kgu-in03@kansaigaidai.ac.jp',
    'charlottechou@ntu.edu.tw',
    'govisiting@deps.ntnu.edu.tw',
    'incoming@uc3m.es',
    'incoming@hs-duesseldorf.de',
    'exchangeunav@unav.es',
    'mobility@karelia.fi',
    'dri-students-exchange-outside-europe@unistra.fr',
    'advisor4asia@unsw.edu.au',
    'incoming@kwansei.ac.jp',
    'incoming.moblity@unive.it',
    'internacional@uao.es',
    'incoming@mruni.eu',
    'kokusai@adm.fukuoka-u.ac.jp',
    'incoming-exchange@univ-paris1.fr',
    'loic.hennemont@galilee.be',
    'incoming@fu-berlin.de',
    'incoming@uib.no',
    'etudiantetranger@uvsq.fr',
    'iro-incoming-sbe@maastrichtuniversity.nl',
    'international-fassl@hva.nl',
    'kokusai@keiho-u.ac.jp',
    'study.abroad@ust.hk',
    'inbound@andrew.ac.jp',
    'incoming.rih@uni-rostock.de',
    'tiina.savela@jyu.fi',
    'intl.interu.entrants@unicaen.fr',
    'nadine.kersten@kuleuven.be',
    'overseas-in@zv.tu-darmstadt.de',
    'incoming-exchange@ruc.dk',
    'uab.exchange.programme@uab.cat',
    'exchange@pku.edu.cn',
    'studyabroad@latrobe.edu.au',
    'bilateral.exchange@usc.es',
    'exchange@yorku.ca',
    'brandon-paulson@uiowa.edu',
    'globalopportunities@uclan.ac.uk',
    'interstu@smith.edu',
    'alizee.leducq@univ-catholille.fr',
    'aform.extraeumobility@unibo.it',
    'sepin@mail.fju.edu.tw',
    'incoming@uni-flensburg.de',
    'exchange@oita-u.ac.jp',
    'm.buisson1@psbedu.paris',
    'ic-inbound@adst.keio.ac.jp',
    'rikkyo-inbound@rikkyo.ac.jp',
    'erasmus@international.uni-halle.de',
    'mobility@uu.se',
    'ryugakusei@cc.nara-wu.ac.jp',
    'auix@oa.tku.edu.tw',
    'nupace@iee.nagoya-u.ac.jp',
    'oieadvising@willamette.edu',
    'rwangui@csudh.edu',
    'mob-in@inalco.fr',
    'isep.inbound@smu.edu.sg',
    'candidature. echange@sciencespo.fr',
    'int.feb@ugent.be'
];

const numFor1Semester = [
    2, 2, 1, 2, 1, 3, 3, 1, 2, 2,
    1, 2, 2, 1, 2, 3, 4, 2, 2, 3,
    1, 3, 2, 1, 1, 2, 2, 2, 3, 3,
    4, 2, 3, 3, 2, 2, 6, 1, 2, 2,
    2, 1, 2, 3, 2, 2, 3, 4, 2, 5,
    2, 3, 4, 2, 1, 3, 2, 2, 2, 2,
    3, 2, 4, 2, 2, 1, 2, 2, 20, 2,
    1, 2, 1, 3, 2, 2, 2, 4, 1, 3,
    1, 3, 3, 3, 1, 2, 1, 1, 2, 2,
    5, 3, 3, 8, 4, 3, 1, 2
];


const semesterStartDates = [
    "Approx. August 12th, 2024",
    "18-Aug-24",
    "Classes begin August 28th, 2024",
    "August 26th, 2024",
    "20-Aug-24",
    "23.09.2024",
    "1st/2nd week of September, 2024",
    "August 22nd, 2024 (tentative)",
    "https://manoa.hawaii.edu/mix/wp-content/uploa",
    "26-Aug-24",
    "19-Aug-24",
    "August 13th, 2024",
    "2nd October 2024",
    "16th September 2024",
    "26-Aug-24",
    "2 Sep 2024 (Provisional)",
    "22-Aug-24",
    "26-Aug-24",
    "https://www.manchester.ac.uk/discover/key-dat",
    "02-Sep-24",
    "16 September, 2024",
    "see calendar",
    "04-Sep-24",
    "28-Aug-24",
    "Sept 3",
    "1st of September",
    "1st October",
    "20-Sep",
    "01.09.2024",
    "End of August (to be confirmed)",
    "September 9th, 2024 (tbc)",
    "Early September",
    "https://www.kansaigaidai.ac.jp/asp/academics/",
    "early September",
    "early September 2024 (TBA)",
    "September 23rd, 2024",
    "To Be Determined - probably Sep 2nd 2024",
    "1 September 2024 (official semester start. Ho",
    "Sept 2nd,2024",
    "15th August 2024 (tbc)",
    "Beginning of September 2024",
    "09 September 2024 Term 3",
    "early September",
    "not available at the moment, it will be updat",
    "Academic Calendar will be available on Februa",
    "1st September, 2024",
    "Not decided but usually September 1.",
    "Not define yet",
    "September 2nd 2024 (TBC)",
    "October 1st, 2024",
    "https://www.uib.no/en/education/49211/semeste",
    "Beginning of September 2024",
    "Late August/begin September.",
    "2002-09-24",
    "30 September, 2024",
    "02-Sep-24",
    "September 26th, 2024",
    "October 1th, 2024",
    "https://www.jyu.fi/en/for-students/kandi-ja-m",
    "09.02.2024",
    "September, 2024 (date is not available)",
    "16 September 2024",
    "October 1st, 2024",
    "01-Sep-14",
    "September 12th 2024 (tentative)",
    "24-Sep",
    "https://www.latrobe.edu.au/calendar/academic-",
    "September, 11th 2024",
    "Varies by location",
    "https://registrar.yorku.ca/enrol/dates",
    "26-Aug-24",
    "30th September 2024",
    "Tuesday, September 3",
    "End of August",
    "Early September",
    "early September",
    "September 1st, 2024",
    "October 1st, 2024 (scheduled)",
    "26-Sep-24",
    "TBA (beginning of September)",
    "01-Oct-24",
    "20-Sep-24",
    "01.10.2024",
    "02-Sep-24",
    "October 1st, 2024",
    "mid-September 2024(TBC)",
    "02-Oct-24",
    "26-Aug-24",
    "19-Aug-24",
    "Around September 24. The date will be determi",
    "Sept 13th 2024 (exact date TBC)",
    "Check with the BFH department in question",
    "1 October 2024 (tentative)",
    "19-Aug-24",
    "02-Sep-24",
    "01-Oct-24",
    "Not decided, but it will be at the end of Sep",
    "Friday, September 20th, 2024"
];


const semesterEndDates = [
    "Approx. December 13, 2024",
    "17-Dec-24",
    "Exams end on December 13, 2024",
    "December 17th, 2024",
    "15-Dec-24",
    "12.01.2025",
    "end of December 2024",
    "December 12th, 2024 (tentative)",
    "https://manoa.hawaii.edu/mix/wp-content/uploa",
    "18-Dec-24",
    "14-Dec-24",
    "December 14th, 2024",
    "16th December 2024",
    "13th December 2024",
    "14-Dec-24",
    "20 Dec 2024 (Provisional)",
    "17-Dec-24",
    "21-Dec-24",
    "https://www.manchester.ac.uk/discover/key-dat",
    "28-Feb-25",
    "Dates not yet available",
    "see calendar",
    "18-Dec-24",
    "12/13/2024",
    "18-Dec",
    "end of January (exact date not known yet)",
    "31st March",
    "31-Mar",
    "28.02.2025",
    "End of December (to be confirmed)",
    "December 20th, 2024",
    "Late June",
    "https://www.kansaigaidai.ac.jp/asp/academics/",
    "late December",
    "late December 2024 (TBA)",
    "February 15th, 2025",
    "To Be Determined - probably January 23rd 2025",
    "28 February 2025 (official semester end. Howe",
    "Dec 20th, 2024",
    "13th December 2024 (tbc)",
    "End of January 2024",
    "05-Dec-24",
    "Late January",
    "not available at the moment, it will be updat",
    "Academic Calendar will be available on Februa",
    "end of January, usually around 28th January",
    "Not decided but usually January 31.",
    "Not define yet",
    "December 20th 2024 (English program), end of",
    "February 28th, 2025",
    "https://www.uib.no/en/education/49211/semeste",
    "Mid January 2025",
    "Late January/begin February.",
    "31-01-2025",
    "3 February, 2025",
    "20-Dec-24",
    "January 27th, 2025",
    "March 31th, 2025",
    "https://www.jyu.fi/en/for-students/kandi-ja-m",
    "12/20/2024",
    "December, 2024 (date is not available)",
    "February 1st 2025",
    "31-Mar-25",
    "31-Jan-25",
    "Desember 20th, 2024 (tentative)",
    "25-Jan",
    "https://www.latrobe.edu.au/calendar/academic-",
    "Febraury 5th 2025",
    "Varies by location",
    "https://registrar.yorku.ca/enrol/dates",
    "20-Dec-24",
    "17.01.2025",
    "Wednesday, December 18",
    "End of December",
    "End of February",
    "early January",
    "February 28th, 2025, (end of exams: probaly m",
    "Late January to early February 2025 (exam dat",
    "March 31, 2025 (The program ends on January 3",
    "TBA (mid-December)",
    "01-Feb-25",
    "03-Feb-25",
    "01.03.2024",
    "19-Jan-25",
    "March 31st, 2025",
    "early-January , 2025(TBC)",
    "05-Feb-25",
    "12-Dec-24",
    "19-Dec-24",
    "Beging of February. The date will be determin",
    "January 10th, 2025 (exact date TBC)",
    "Check with the BFH department in question",
    "Early February 2025 (tentative)",
    "08-Dec-24",
    "20-Dec-24",
    "early February 2025",
    "March 31st 2024",
    "Saturday, February 1st, 2025"
];

const courseRestrictions = [
    "no",
    "Students register for courses upon arrival and must have flexibility in their requirements",
    "Architecture (requires portfolio review); Computer and Information Science; Performing Arts (Dance, Music, Theater); Business (unless majoring/minoring in business at your home university); Education; Professional Schools (Dentistry, Law, Medicine, Pharmacy, Podiatry); Visual Arts (Film/Media Arts, Graphic Design, Fine Arts)",
    "Exchange students are eligible for enrollment in our College of Arts and Sciences only (not Business, Engineering, Education, Pharmacy, Agriculture, Social Work, etc.)",
    "Psychology modules are restricted to students from Partners we have a Psychology agreement with. Computer Science modules have restrictions on a module-by-module basis",
    "Students are not permitted to take 300 or 400 level courses in a subject that is not your major of study.",
    "Students cannot enroll in Graduate Level courses (MA, PhD, etc.) They cannot enroll in metroversity courses and have to follow US Department of State guidelines on how many online courses they can enroll in. Students from Ewha planning to attend Bellarmine should have some flexibility in their course selection options because Bellarmine courses have small classes sizes so sometimes courses fill to capacity before Exchange students can register and other courses are not offered every semester.",
    "Must meet prerequisites; may experience capacity issues with some course areas",
    "Courses Restricted: PHARMACY, MEDICAL SCIENCE, and NURSING are NOT allowed to be taken. NUTRITION, LAW, and ARCHITECTURE are restricted.",
    "Some courses require prerequisute courses in order for students to register. To waive the prerequisute requirement, exchange students must contact the course instructor or other contact in charge of waiving this requiirement. Our office helps assist students in this process.",
    "Please restrictions for more info at the bottom of this page: https://www.kcl.ac.uk/abroad/module-options",
    "Students can not take courses in the School of Communication. For all other courses must meet stated prerequisites. https://www.american.edu/abroadatau/academics.cfm",
    "The following programmes/courses are NOT opened to incoming students: Faculty of Dentistry, Li Ka Shing Faculty of Medicine, BSc (Exercise and Health) Programme, Most final year project courses provided by all faculties",
    "Exchange students may not enroll in these courses: graduate level courses (labeled 4999 and above), courses in the fields of interior design & architecture, law, nursing, medicine, or courses in the Semester in Washington Program (denoted as PGMT).",
    "No",
    "Architecture students need to prove basic German skills (level A2)",
    "Applicants must have completed at least one academic year on a bachelor's level. Further students must be officially nominated by their home university and must submit the application dossier within the deadline. Once nominated students will receive an e-mail inviting them to apply. A study programme of at least 15 ECTS per semester is required by our university.",
    "Restrictions and limitations • There is a limited availability of courses at the Lund University School of Economics and Management (LUSEM). Students applying through a university-wide agreement can at most be accepted to 15 credits at LUSEM per semester. • There is a limited availability of non-clinical courses on masters level at the Faculty of Medicine for students on university-wide agreements. The Faculty of Medicine mainly admit students within specific faculty/department agreements. • There is a limited availability of courses in Molecular Biology. • Courses in Bioinformatics are not available. • Courses at the School of Industrial Design are not available for students applying through a university-wide agreement. • Courses in Journalism are not available. • The Faculty of Fine and Performing Arts, (including Malmö Academy of Music, Malmö Art Academy and Malmö Theatre Academy) mainly admit students within specific faculty/department agreements. • Note, not all courses in English are open to exchange students.",
    "Students can take any course provided they meet the pre-requisite requirements for that course. Students cannot enroll in Nursing and Trades &Technology",
    "Nursing is not offered to exchange students and in some cases for upper-level courses, instructor permission is needed.",
    "We cannot accept exchnage students in Pharmacy, Medicine and Nursing. Some restrictions also for Architecture.",
    "Students can't take classes of 2nd year Master",
    "Exchange students cannot attend 1st year courses",
    "No",
    "No",
    "Architecture students need to prove basic German skills (level A2)",
    "Exchange students cannot attend 1st year courses",
    "No",
    "No",
    "no restrictions",
    "No",
    "No",
    "N/A",
    "Exchange students can only take courses from our Exchange program (https://studiekiezer.ugent.be/2024/exchange-programme-in-economics-and-business-administration/programma)",
    "no restrictions",
    "No",
    "Peace and Conflict Studies course (Master) and Doctoral programs are not open to exchange students.",
    "N/A",
    "Exchange students can only take courses from our Exchange program (https://studiekiezer.ugent.be/2024/exchange-programme-in-economics-and-business-administration/programma)"
];




export {
    universityNames, country, city, grade, language, language2, dormitory,
    websiteLinks, scheduleLinks, email, numFor1Semester, semesterStartDates, semesterEndDates, courseRestrictions
};